#lang racket

(define (make-account balance pw)
  (define (withdraw amount)
    (if (and (> amount 0) (>= balance amount))
        (begin (set! balance (- balance amount))
               balance)
        (error "Invalid amount" amount)))
  (define (deposit amount)
    (if (> amount 0)
        (begin (set! balance (+ balance amount))
               balance)
        (error "Invalid amount" amount)))
  (define (dispatch m p)
    (if (eq? p pw)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Invalid command" m)))
        (lambda (amount) "Invalid password")))
  dispatch)

(define acc (make-account 100 'secret-pass))
((acc 'withdraw 'secret-pass) 40)
((acc 'deposit 'secret-pass) 30)