#lang racket

(define (make-account balance pw)
  (let ((wrong-pw-count 0)
        (wrong-pw-limit 6))
    (define (withdraw amount)
      (if (and (> amount 0) (>= balance amount))
          (begin (set! balance (- balance amount))
                 balance)
          (error "Invalid amount" amount)))
    (define (deposit amount)
      (if (> amount 0)
          (begin (set! balance (+ balance amount))
                 balance)
          (error "Invalid amount" amount)))
    (define (dispatch m p)
      (if (eq? p pw)
          (begin (set! wrong-pw-count 0)
                 (cond ((eq? m 'withdraw) withdraw)
                       ((eq? m 'deposit) deposit)
                       (else (error "Invalid command" m))))
          (if (> wrong-pw-count wrong-pw-limit)
              (lambda (amount) "Wrong password limit reached, account locked")
              (lambda (amount)
                (begin (set! wrong-pw-count (+ wrong-pw-count 1))
                       "Invalid password, please try again")))))
    dispatch))

(define acc (make-account 100 'secret-pass))
((acc 'withdraw 'secret-pass) 40)
((acc 'deposit 'secret-pass) 30)
((acc 'deposit 'wrongpw) 30)
((acc 'deposit 'secret-pass) 30)
((acc 'deposit 'wrongpw) 30)
((acc 'deposit 'wrongpw) 30)
((acc 'deposit 'wrongpw) 30)
((acc 'deposit 'wrongpw) 30)
((acc 'deposit 'wrongpw) 30)
((acc 'deposit 'wrongpw) 30)
((acc 'deposit 'wrongpw) 30)
((acc 'deposit 'wrongpw) 30)